### Python Program

#### 1. Write a python program to count the number of letters in a given string using list only
      Input : 'aabacbdea'
      Expected Output : a:4 b:2 c:1 d:1 e:1

In [3]:
s = 'aabacbdea'
  # Expected Output : a:4 b:2 c:1 d:1 e:1

d = {}

for i in s:
    if i in d:
        d[i] = d[i] + 1
    else:
        d[i] = 1

d

{'a': 4, 'b': 2, 'c': 1, 'd': 1, 'e': 1}

### 2. Write a code to reverse a string without using any predefined (available) python functions. Use only lists
        
      Input : 'ABCDCBA'

In [5]:
s = 'ABCDCBA123'
s1 = ""
len_s = len(s)
for i,k in enumerate(s):
    s1 += s[len_s-1-i]

print(s1)

321ABCDCBA

#### 3. From a log file that contains user login and logout events in the following format:
```YYYY-MM-DD HH:MM:SS Username logged in/out```
Extract and sort users based on their total logged in time based on following instructions.

##### 3.a Read the login_log.txt file

##### 3.b. Extract login and log out time of each user using re module and store it into a dictionary

In [ ]:
i

##### 3.c. Calculate the total time a user was logged in

In [ ]:
!ls

##### 3.d. Sort users list based on their total logged in time in descending order

### Pandas Understanding 

You are supposed to write code for the questions below using train data file . For better understanding of data you refer to Big Sales Mart Problem.docx .

#### 1. Read the train data file.

In [6]:
import  pandas as pd

In [13]:
df = pd.read_excel("Train.xlsx")
df.shape

(8523, 12)

In [14]:
df.head(2)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228

In [24]:
df[["Outlet_Size", "Item_Weight"]].head()

  Outlet_Size  Item_Weight
0      Medium         9.30
1      Medium         5.92
2      Medium        17.50
3         NaN        19.20
4        High         8.93

In [15]:
df.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [19]:
df.describe()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,7060.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,12.857645,0.066132,140.992782,1997.831867,2181.288914
std,4.643456,0.051598,62.275067,8.371760,1706.499616
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.773750,0.026989,93.826500,1987.000000,834.247400
50%,12.600000,0.053931,143.012800,1999.000000,1794.331000
75%,16.850000,0.094585,185.643700,2004.000000,3101.296400
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [25]:
df1 = df.copy()

In [31]:
df1["Item_Weight"]= df1["Item_Weight"].fillna(df1["Item_Weight"].mean())

In [35]:
df1.isna().sum()

np.int64(0)

In [33]:
df1["Outlet_Size"]= df1["Outlet_Size"].fillna(df1["Outlet_Size"].mode()[0])

In [20]:
from collections import  Counter as C

In [21]:
C(df["Item_Identifier"])

Counter({'FDG33': 10,
         'FDW13': 10,
         'FDV38': 9,
         'FDX20': 9,
         'FDP25': 9,
         'DRE49': 9,
         'FDV60': 9,
         'NCY18': 9,
         'DRN47': 9,
         'FDW49': 9,
         'FDX31': 9,
         'FDO19': 9,
         'NCJ30': 9,
         'NCF42': 9,
         'FDD38': 9,
         'NCB18': 9,
         'FDG09': 9,
         'NCI54': 9,
         'FDF52': 9,
         'NCL31': 9,
         'FDF56': 9,
         'NCQ06': 9,
         'FDT07': 9,
         'FDW26': 9,
         'FDQ40': 9,
         'FDU12': 9,
         'FDX04': 9,
         'FDA15': 8,
         'FDO10': 8,
         'FDC14': 8,
         'NCX29': 8,
         'FDV20': 8,
         'NCP05': 8,
         'DRK35': 8,
         'FDJ58': 8,
         'FDA44': 8,
         'FDS52': 8,
         'DRK12': 8,
         'FDK58': 8,
         'FDL58': 8,
         'FDR44': 8,
         'FDP28': 8,
         'FDA39': 8,
         'FDH28': 8,
         'DRF27': 8,
         'FDX21': 8,
         'FDY56': 8,
         'FDF05': 8,
         'FDL20': 8,
         'FDY03': 8,
         'FDJ55': 8,
         'FDG24': 8,
         'FDY55': 8,
         'FDH27': 8,
         'FDR04': 8,
         'FDS33': 8,
         'FDY49': 8,
         'FDR59': 8,
         'FDR43': 8,
         'FDW24': 8,
         'FDF22': 8,
         'DRP35': 8,
         'FDB17': 8,
         'NCO54': 8,
         'FDA13': 8,
         'FDR52': 8,
         'NCM07': 8,
         'NCI29': 8,
         'FDD29': 8,
         'NCQ43': 8,
         'DRF03': 8,
         'FDT32': 8,
         'FDK20': 8,
         'FDU13': 8,
         'FDZ26': 8,
         'FDL34': 8,
         'DRF01': 8,
         'FDG38': 8,
         'NCE31': 8,
         'NCL53': 8,
         'NCQ05': 8,
         'NCV06': 8,
         'FDO52': 8,
         'FDR23': 8,
         'FDI41': 8,
         'DRJ24': 8,
         'FDT21': 8,
         'NCB31': 8,
         'FDN56': 8,
         'FDX50': 8,
         'FDH10': 8,
         'FDD05': 8,
         'DRF23': 8,
         'FDT49': 8,
         'FDG57': 8,
         'FDZ33': 8,
         'FDR46': 8,
         'FDF04': 8,
         'FDH33': 8,
         'FDP11': 8,
         'FDW48': 8,
         'FDA50': 8,
         'FDR48': 8,
         'NCY29': 8,
         'FDX45': 8,
         'FDJ44': 8,
         'NCK29': 8,
         'FDF16': 8,
         'FDZ21': 8,
         'NCV41': 8,
         'FDA04': 8,
         'NCK05': 8,
         'NCE54': 8,
         'FDZ20': 8,
         'NCX05': 8,
         'FDO32': 8,
         'FDT55': 8,
         'FDQ39': 8,
         'FDE11': 8,
         'FDT40': 8,
         'FDT24': 8,
         'DRA59': 8,
         'FDS55': 8,
         'FDX58': 8,
         'DRD25': 8,
         'FDY47': 8,
         'FDU23': 8,
         'FDV09': 8,
         'FDI22': 8,
         'NCS53': 8,
         'FDL10': 8,
         'FDO37': 8,
         'NCC18': 8,
         'FDV26': 8,
         'DRI03': 8,
         'NCK53': 8,
         'FDU19': 8,
         'FDN15': 7,
         'FDP10': 7,
         'FDH17': 7,
         'FDY07': 7,
         'FDX32': 7,
         'FDP49': 7,
         'DRI11': 7,
         'FDU02': 7,
         'FDW12': 7,
         'NCB30': 7,
         'FDE51': 7,
         'FDO23': 7,
         'FDB34': 7,
         'NCP18': 7,
         'FDK21': 7,
         'NCX54': 7,
         'FDI26': 7,
         'FDC46': 7,
         'FDH19': 7,
         'NCZ18': 7,
         'FDC29': 7,
         'FDQ10': 7,
         'FDN04': 7,
         'FDV45': 7,
         'NCL18': 7,
         'DRI25': 7,
         'FDB56': 7,
         'FDD10': 7,
         'DRB48': 7,
         'FDH14': 7,
         'DRK49': 7,
         'FDD17': 7,
         'FDB14': 7,
         'FDL40': 7,
         'DRG23': 7,
         'NCR53': 7,
         'NCN07': 7,
         'FDI04': 7,
         'FDB36': 7,
         'DRD24': 7,
         'DRL01': 7,
         'NCM43': 7,
         'FDM15': 7,
         'FDS31': 7,
         'FDI32': 7,
         'FDO24': 7,
         'FDV39': 7,
         'NCO17': 7,
         'FDT12': 7,
         'FDT43': 7,
         'FDN57': 7,
         'FDS45': 7,
         'FDX40': 7,
         'NCZ54': 7,
         'FDT25': 7,
         'NCX42': 7,
         'FDG08': 7,
         'FDN01': 7,
         'FDQ56': 7,
         'FDK51': 7,
         'FDL22': 7,
         'FDY59': 7,
         'FDE33': 7,
         'FDU36': 7,
         'FDX19': 7,
         'FDA01': 7,
         'FDY31': 7,
         'DRQ35': 7,
         'FDX36': 7,
         'DRD13': 7,
         'FDZ35': 7,
         'FDN60': 7,
         'FDC41': 7,
         'FDJ22': 7,
         'DRI01': 7,
         'FDH26': 7,
         'FDX26': 7,
         'NCW53': 7,
         'FDL52': 7,
         'FDC50': 7,
         'FDW07': 7,
         'NCE19': 7,
         'FDR02': 7,
         'NCR05': 7,
         'NCJ18': 7,
         'FDW28': 7,
         'FDU46': 7,
         'FDZ15': 7,
         'NCS54': 7,
         'FDU25': 7,
         'FDR21': 7,
         'FDH57': 7,
         'FDV57': 7,
         'FDE16': 7,
         'FDB15': 7,
         'FDL48': 7,
         'DRD37': 7,
         'FDU21': 7,
         'FDI14': 7,
         'FDW50': 7,
         'FDU38': 7,
         'FDS32': 7,
         'FDO22': 7,
         'FDJ21': 7,
         'FDC17': 7,
         'NCH30': 7,
         'FDL46': 7,
         'FDZ52': 7,
         'FDR58': 7,
         'NCE07': 7,
         'FDP24': 7,
         'FDM08': 7,
         'NCG43': 7,
         'FDS19': 7,
         'NCH55': 7,
         'NCV54': 7,
         'NCU17': 7,
         'NCZ06': 7,
         'NCQ53': 7,
         'FDH21': 7,
         'NCQ38': 7,
         'FDS28': 7,
         'FDO34': 7,
         'FDY02': 7,
         'FDD50': 7,
         'FDK26': 7,
         'FDY35': 7,
         'FDN12': 7,
         'FDP03': 7,
         'NCP50': 7,
         'FDV01': 7,
         'FDS27': 7,
         'DRM59': 7,
         'FDJ57': 7,
         'FDJ45': 7,
         'NCY41': 7,
         'FDQ08': 7,
         'FDS47': 7,
         'FDZ08': 7,
         'FDR27': 7,
         'NCI31': 7,
         'DRM37': 7,
         'FDF21': 7,
         'FDL38': 7,
         'DRL37': 7,
         'FDN21': 7,
         'FDZ23': 7,
         'FDT34': 7,
         'FDO57': 7,
         'FDM36': 7,
         'NCP06': 7,
         'FDI57': 7,
         'FDI45': 7,
         'FDE17': 7,
         'FDS16': 7,
         'NCD54': 7,
         'FDL13': 7,
         'NCM06': 7,
         'FDT46': 7,
         'DRA24': 7,
         'FDG34': 7,
         'FDU34': 7,
         'FDY15': 7,
         'FDW09': 7,
         'DRD15': 7,
         'FDV04': 7,
         'FDF57': 7,
         'FDA02': 7,
         'FDK38': 7,
         'NCZ30': 7,
         'FDK08': 7,
         'DRM23': 7,
         'FDP60': 7,
         'FDV28': 7,
         'FDU20': 7,
         'FDI20': 7,
         'DRF25': 7,
         'FDR55': 7,
         'FDB58': 7,
         'FDW19': 7,
         'NCX18': 7,
         'FDD57': 7,
         'FDB04': 7,
         'FDC59': 7,
         'NCL29': 7,
         'FDW38': 7,
         'FDY33': 7,
         'FDZ58': 7,
         'FDH50': 7,
         'FDS01': 7,
         'FDW34': 7,
         'DRE03': 7,
         'NCK18': 7,
         'FDR37': 7,
         'FDX47': 7,
         'FDP39': 7,
         'FDO60': 7,
         'NCS06': 7,
         'NCO05': 7,
         'FDR35': 7,
         'FDK03': 7,
         'DRC25': 7,
         'NCG07': 7,
         'NCH07': 7,
         'NCL05': 7,
         'FDK40': 7,
         'NCM29': 7,
         'FDW32': 7,
         'FDQ34': 7,
         'FDR01': 7,
         'FDA32': 7,
         'DRG37': 7,
         'DRL35': 7,
         'FDS13': 7,
         'FDL36': 7,
         'DRJ11': 7,
         'FDS40': 7,
         'FDQ36': 7,
         'FDG50': 7,
         'DRE48': 7,
         'FDV16': 7,
         'FDS04': 7,
         'FDS57': 7,
         'NCM30': 7,
         'FDM58': 7,
         'FDI07': 7,
         'FDT03': 7,
         'FDJ09': 7,
         'DRL60': 7,
         'FDQ26': 7,
         'NCA06': 7,
         'FDI21': 7,
         'FDR15': 7,
         'FDR09': 7,
         'FDJ48': 7,
         'DRD12': 7,
         'FDC16': 7,
         'FDY57': 7,
         'FDP27': 7,
         'NCO29': 7,
         'FDM44': 7,
         'FDY13': 7,
         'NCN53': 7,
         'FDS59': 7,
         'FDH48': 7,
         'FDU26': 7,
         'FDA07': 7,
         'FDD39': 7,
         'NCS30': 7,
         'FDH56': 7,
         'FDG32': 7,
         'FDV19': 7,
         'FDR22': 7,
         'DRC01': 6,
         'FDX07': 6,
         'NCD19': 6,
         'FDA03': 6,
         'NCB42': 6,
         'DRJ59': 6,
         'FDP33': 6,
         'DRZ11': 6,
         'FDK43': 6,
         'FDA46': 6,
         'FDC02': 6,
         'FDV49': 6,
         'FDY21': 6,
         'FDF09': 6,
         'FDY40': 6,
         'FDY45': 6,
         'DRH37': 6,
         'NCI17': 6,
         'FDH35': 6,
         'FDL04': 6,
         'FDD58': 6,
         'FDR12': 6,
         'FDZ55': 6,
         'NCR17': 6,
         'FDF41': 6,
         'FDT28': 6,
         'FDA47': 6,
         'FDG12': 6,
         'DRE60': 6,
         'FDW39': 6,
         'FDX34': 6,
         'FDZ16': 6,
         'DRA12': 6,
         'DRJ13': 6,
         'FDJ38': 6,
         'NCP30': 6,
         'NCH54': 6,
         'NCO26': 6,
         'FDB51': 6,
         'FDX44': 6,
         'FDI16': 6,
         'NCI18': 6,
         'FDN13': 6,
         'DRF49': 6,
         'FDW51': 6,
         'FDB35': 6,
         'NCU05': 6,
         'DRY23': 6,
         'FDO08': 6,
         'NCW29': 6,
         'FDE04': 6,
         'NCB19': 6,
         'FDV15': 6,
         'FDA08': 6,
         'FDT20': 6,
         'FDB41': 6,
         'FDE36': 6,
         'FDI19': 6,
         'FDF24': 6,
         'DRF36': 6,
         'DRC27': 6,
         'FDE10': 6,
         'FDX15': 6,
         'FDL56': 6,
         'DRM47': 6,
         'NCR38': 6,
         'FDU44': 6,
         'FDL43': 6,
         'FDV32': 6,
         'FDJ34': 6,
         'FDS12': 6,
         'FDG29': 6,
         'FDG59': 6,
         'FDM28': 6,
         'FDZ10': 6,
         'NCF07': 6,
         'FDM25': 6,
         'FDF20': 6,
         'FDX23': 6,
         'FDD40': 6,
         'FDB29': 6,
         'FDC08': 6,
         'FDB45': 6,
         'NCK19': 6,
         'FDV51': 6,
         'DRH39': 6,
         'FDN58': 6,
         'FDM01': 6,
         'DRI37': 6,
         'NCO30': 6,
         'FDN39': 6,
         'FDH40': 6,
         'FDX60': 6,
         'FDG45': 6,
         'FDD44': 6,
         'FDS15': 6,
         'FDL51': 6,
         'FDX09': 6,
         'FDB27': 6,
         'FDY28': 6,
         'FDT57': 6,
         'FDP22': 6,
         'NCJ29': 6,
         'FDT59': 6,
         'NCX41': 6,
         'FDS48': 6,
         'FDZ38': 6,
         'FDW35': 6,
         'FDW23': 6,
         'DRH03': 6,
         'FDW27': 6,
         'FDJ41': 6,
         'FDE24': 6,
         'FDH53': 6,
         'DRI51': 6,
         'FDT09': 6,
         'FDK41': 6,
         'FDQ45': 6,
         'DRK59': 6,
         'FDN09': 6,
         'NCK54': 6,
         'FDK24': 6,
         'FDD08': 6,
         'FDR60': 6,
         'FDV37': 6,
         'FDG53': 6,
         'NCR41': 6,
         'FDW44': 6,
         'FDT31': 6,
         'FDT08': 6,
         'FDC53': 6,
         'FDQ09': 6,
         'FDL08': 6,
         'FDE34': 6,
         'NCF31': 6,
         'FDR08': 6,
         'NCQ50': 6,
         'FDQ48': 6,
         'FDK14': 6,
         'FDX46': 6,
         'FDC35': 6,
         'FDH45': 6,
         'FDX33': 6,
         'NCQ42': 6,
         'FDE05': 6,
         'FDR20': 6,
         'FDH32': 6,
         'NCJ42': 6,
         'FDE32': 6,
         'FDU11': 6,
         'FDK15': 6,
         'FDU32': 6,
         'FDC33': 6,
         'DRH25': 6,
         'NCI43': 6,
         'FDX57': 6,
         'FDA23': 6,
         'FDR26': 6,
         'FDG21': 6,
         'FDI28': 6,
         'FDA10': 6,
         'FDS03': 6,
         'FDO15': 6,
         'FDZ04': 6,
         'DRB25': 6,
         'NCO06': 6,
         'FDK34': 6,
         'FDO45': 6,
         'FDF08': 6,
         'FDH58': 6,
         'FDG44': 6,
         'FDH20': 6,
         'FDL24': 6,
         'FDQ15': 6,
         'FDN23': 6,
         'FDS44': 6,
         'FDA21': 6,
         'NCK17': 6,
         'DRD60': 6,
         'FDQ31': 6,
         'FDK55': 6,
         'DRG15': 6,
         'FDT10': 6,
         'FDN02': 6,
         'DRE27': 6,
         'FDK02': 6,
         'FDT50': 6,
         'FDJ60': 6,
         'FDW46': 6,
         'FDU40': 6,
         'DRE12': 6,
         'FDD51': 6,
         'FDR19': 6,
         'FDZ12': 6,
         'FDX16': 6,
         'NCA05': 6,
         'NCR30': 6,
         'FDP19': 6,
         'NCN14': 6,
         'FDQ21': 6,
         'FDZ39': 6,
         'FDS35': 6,
         'FDZ56': 6,
         'NCN43': 6,
         'FDW56': 6,
         'FDF34': 6,
         'FDD04': 6,
         'DRK11': 6,
         'DRJ39': 6,
         'FDZ44': 6,
         'FDV46': 6,
         'FDZ25': 6,
         'FDG31': 6,
         'NCP29': 6,
         'FDU15': 6,
         'FDO09': 6,
         'FDB40': 6,
         'FDE41': 6,
         'FDN34': 6,
         'FDL39': 6,
         'FDD21': 6,
         'FDV22': 6,
         'NCB43': 6,
         'FDQ46': 6,
         'FDC44': 6,
         'FDL33': 6,
         'FDO40': 6,
         'FDG16': 6,
         'NCM05': 6,
         'FDA49': 6,
         'FDY52': 6,
         'FDD09': 6,
         'FDY36': 6,
         'FDD46': 6,
         'FDY10': 6,
         'FDA28': 6,
         'FDK45': 6,
         'FDM51': 6,
         'FDV44': 6,
         'FDG46': 6,
         'NCN05': 6,
         'FDO58': 6,
         'NCP55': 6,
         'FDW45': 6,
         'FDT48': 6,
         'NCH18': 6,
         'FDG47': 6,
         'NCO41': 6,
         'FDG26': 6,
         'FDQ32': 6,
         'FDE29': 6,
         'FDN46': 6,
         'FDT58': 6,
         'FDO50': 6,
         'DRK13': 6,
         'FDR32': 6,
         'FDH05': 6,
         'FDD52': 6,
         'NCZ17': 6,
         'FDZ48': 6,
         'FDE59': 6,
         'FDO46': 6,
         'FDI50': 6,
         'FDB60': 6,
         'FDA20': 6,
         'DRF37': 6,
         'FDX56': 6,
         'FDZ49': 6,
         'FDW02': 6,
         'FDL57': 6,
         'FDF12': 6,
         'FDD47': 6,
         'FDK52': 6,
         'FDB08': 6,
         'FDX43': 6,
         'FDL09': 6,
         'FDG56': 6,
         'FDI56': 6,
         'FDT11': 6,
         'NCU54': 6,
         'NCO02': 6,
         'FDM04': 6,
         'NCX30': 6,
         'DRI47': 6,
         'FDZ59': 6,
         'FDL45': 6,
         'FDC45': 6,
         'FDQ52': 6,
         'FDT26': 6,
         'FDP44': 6,
         'FDS11': 6,
         'DRE15': 6,
         'NCI42': 6,
         'FDX37': 6,
         'FDZ45': 6,
         'FDB23': 6,
         'FDY04': 6,
         'NCG30': 6,
         'FDH44': 6,
         'NCN19': 6,
         'NCI30': 6,
         'NCA53': 6,
         'FDS56': 6,
         'FDJ10': 6,
         'NCH43': 6,
         'FDS23': 6,
         'FDJ53': 6,
         'FDX01': 6,
         'DRF13': 6,
         'FDK25': 6,
         'FDC20': 6,
         'FDS24': 6,
         'DRH36': 6,
         'FDV48': 6,
         'FDE46': 6,
         'NCO42': 6,
         'FDD41': 6,
         'NCK07': 6,
         'FDW47': 6,
         'NCU42': 6,
         'FDS37': 6,
         'FDO25': 6,
         'FDI52': 6,
         'DRO47': 6,
         'NCL41': 6,
         'FDD56': 6,
         'FDQ13': 6,
         'FDB49': 6,
         'FDH41': 6,
         'FDF26': 6,
         'DRI23': 6,
         'NCJ05': 6,
         'FDU24': 6,
         'FDX11': 6,
         'FDD26': 6,
         'FDO39': 6,
         'FDD11': 6,
         'FDJ04': 6,
         'NCT42': 6,
         'FDX03': 6,
         'NCU18': 6,
         'FDK09': 6,
         'NCC07': 6,
         'FDT36': 6,
         'FDH38': 6,
         'DRJ01': 6,
         'NCE30': 6,
         'FDB32': 6,
         'FDG10': 6,
         'FDW59': 6,
         'FDD14': 6,
         'NCD18': 6,
         'FDU51': 6,
         'FDI60': 6,
         'FDN38': 6,
         'FDU39': 6,
         'FDO20': 6,
         'FDV47': 6,
         'FDI15': 6,
         'DRN37': 6,
         'FDU33': 6,
         'FDU07': 6,
         'NCN30': 6,
         'FDK33': 6,
         'NCC54': 6,
         'FDR33': 6,
         'DRL49': 6,
         'NCT30': 6,
         'FDQ58': 6,
         'FDC47': 6,
         'FDH47': 6,
         'FDI08': 6,
         'FDY48': 6,
         'DRN35': 6,
         'FDC34': 6,
         'FDO12': 6,
         'FDY50': 6,
         'FDI34': 6,
         'FDH60': 6,
         'NCF30': 6,
         'FDZ09': 6,
         'NCS29': 6,
         'FDS36': 6,
         'FDU28': 5,
         'FDS46': 5,
         'FDF32': 5,
         'FDR28': 5,
         'NCD06': 5,
         'FDV10': 5,
         'NCS17': 5,
         'DRH01': 5,
         'FDM39': 5,
         'FDL12': 5,
         'FDS02': 5,
         'FDA43': 5,
         'FDM20': 5,
         'FDZ03': 5,
         'FDG02': 5,
         'FDN48': 5,
         'FDV25': 5,
         'FDG20': 5,
         'FDQ49': 5,
         'DRG27': 5,
         'FDU04': 5,
         'FDW57': 5,
         'FDP09': 5,
         'FDD03': 5,
         'NCF19': 5,
         'FDW11': 5,
         'FDY25': 5,
         'NCO55': 5,
         'NCC30': 5,
         'FDP16': 5,
         'FDB11': 5,
         'NCB06': 5,
         'FDA45': 5,
         'FDK44': 5,
         'FDR47': 5,
         'FDU50': 5,
         'NCX06': 5,
         'NCN55': 5,
         'FDE40': 5,
         'FDX49': 5,
         'NCM53': 5,
         'FDI24': 5,
         'FDG52': 5,
         'FDY24': 5,
         'FDS49': 5,
         'FDX25': 5,
         'NCR18': 5,
         'DRJ51': 5,
         'DRK01': 5,
         'FDY38': 5,
         'NCR54': 5,
         'FDS26': 5,
         'FDJ08': 5,
         'FDT39': 5,
         'FDE08': 5,
         'FDB57': 5,
         'NCT54': 5,
         'FDK36': 5,
         'NCQ54': 5,
         'FDB21': 5,
         'FDM50': 5,
         'FDF46': 5,
         'FDA33': 5,
         'FDB53': 5,
         'FDV59': 5,
         'FDO01': 5,
         'NCO43': 5,
         'FDQ07': 5,
         'FDR24': 5,
         'FDP59': 5,
         'FDT27': 5,
         'FDJ56': 5,
         'FDT22': 5,
         'FDL32': 5,
         'FDZ07': 5,
         'FDF45': 5,
         'FDV02': 5,
         'NCF18': 5,
         'FDG35': 5,
         'FDY34': 5,
         'FDM60': 5,
         'NCZ42': 5,
         'FDF11': 5,
         'FDB44': 5,
         'FDA27': 5,
         'FDN32': 5,
         'FDZ27': 5,
         'FDX08': 5,
         'NCE43': 5,
         'FDQ20': 5,
         'FDO28': 5,
         'FDH16': 5,
         'NCH06': 5,
         'FDM24': 5,
         'NCT41': 5,
         'NCP42': 5,
         'FDA40': 5,
         'NCG42': 5,
         'FDC40': 5,
         'FDE53': 5,
         'FDW31': 5,
         'DRN36': 5,
         'FDQ37': 5,
         'FDK28': 5,
         'FDZ47': 5,
         'NCJ54': 5,
         'NCN18': 5,
         'NCE06': 5,
         'FDN16': 5,
         'FDR49': 5,
         'NCL19': 5,
         'DRG01': 5,
         'FDB38': 5,
         'FDZ22': 5,
         'DRH13': 5,
         'FDJ20': 5,
         'FDE22': 5,
         'DRE25': 5,
         'FDR36': 5,
         'DRK37': 5,
         'FDK48': 5,
         'NCQ41': 5,
         'FDU14': 5,
         'FDZ01': 5,
         'FDS58': 5,
         'FDY51': 5,
         'FDA34': 5,
         'DRK23': 5,
         'FDO27': 5,
         'FDB16': 5,
         'FDF44': 5,
         'NCV05': 5,
         'FDX39': 5,
         'DRI39': 5,
         'NCN29': 5,
         'FDZ28': 5,
         'FDQ51': 5,
         'NCK06': 5,
         'FDB59': 5,
         'FDY26': 5,
         'DRE13': 5,
         'FDC04': 5,
         'FDV07': 5,
         'FDC10': 5,
         'DRK39': 5,
         'FDE02': 5,
         'FDQ23': 5,
         'NCN41': 5,
         'FDO36': 5,
         'FDB09': 5,
         'FDA09': 5,
         'FDO13': 5,
         'FDE35': 5,
         'NCV30': 5,
         'FDM46': 5,
         'FDS21': 5,
         'FDX35': 5,
         'FDY27': 5,
         'NCN06': 5,
         'FDA52': 5,
         'DRG51': 5,
         'FDM56': 5,
         'FDC09': 5,
         'NCZ41': 5,
         'FDQ24': 5,
         'DRL11': 5,
         'FDE45': 5,
         'NCO18': 5,
         'FDX59': 5,
         'FDX27': 5,
         'FDR14': 5,
         'NCL55': 5,
         'FDB39': 5,
         'FDU22': 5,
         'NCC43': 5,
         'FDP48': 5,
         'FDC26': 5,
         'NCJ31': 5,
         'NCY05': 5,

In [22]:
C(df["Outlet_Type"])

Counter({'Supermarket Type1': 5577,
         'Grocery Store': 1083,
         'Supermarket Type3': 935,
         'Supermarket Type2': 928})

In [ ]:
C(df["Outlet_Type"])

In [23]:
C(df.Outlet_Location_Type)

Counter({'Tier 3': 3350, 'Tier 2': 2785, 'Tier 1': 2388})

In [10]:
# !pip install openpyxl

#### 2. Print the total rows and columns count. Also find out null values in each column

#### 3. Filter only numerical columns  and categorical columns separately.

   #### 4. Find
           a) Average item outlet sales and item mrp across different item types
            b)identify item type which has maximum average item outlet sales and item mrp

#### 5. What is the mean item sales as per age of the outlet

#### 6.  Identify and plot correlation for the dataset.

#### 7. What is the max item sales as per outlet size location for different item types

#### 8.Plot the the relationship between item fat and item type

#### 9. Perform one hot encoding and normalisation

#### 10. Build a svm regression model and explain whether the current mode is overfitting or underfitting.

#### 11. Perform prediction on test file

### Embedding model

#### 1. Load following model from HuggingFace using transformers. 
       sentence-transformers/all-mpnet-base-v2

#### 2. Print out context window size of the model using tokenizer object

#### 3. Generate embedding output for input query :  `base architecture of RoBERTa`

### RAG Questions

#### 1. Create chunks of the following text for the given model without using any library:

In [ ]:
document_txt = """
The RoBERTa model was proposed in RoBERTa: A Robustly Optimized BERT Pretraining Approach by Yinhan Liu, Myle Ott, Naman Goyal, Jingfei Du, Mandar Joshi, Danqi Chen, Omer Levy, Mike Lewis, Luke Zettlemoyer, Veselin Stoyanov. It is based on Google’s BERT model released in 2018.
 
It builds on BERT and modifies key hyperparameters, removing the next-sentence pretraining objective and training with much larger mini-batches and learning rates.
 
The abstract from the paper is the following:
 
Language model pretraining has led to significant performance gains but careful comparison between different approaches is challenging. Training is computationally expensive, often done on private datasets of different sizes, and, as we will show, hyperparameter choices have significant impact on the final results. We present a replication study of BERT pretraining (Devlin et al., 2019) that carefully measures the impact of many key hyperparameters and training data size. We find that BERT was significantly undertrained, and can match or exceed the performance of every model published after it. Our best model achieves state-of-the-art results on GLUE, RACE and SQuAD. These results highlight the importance of previously overlooked design choices, and raise questions about the source of recently reported improvements. We release our models and code.
 
This model was contributed by julien-c. The original code can be found here.
 
Usage tips
This implementation is the same as BertModel with a tiny embeddings tweak as well as a setup for Roberta pretrained models.
 
RoBERTa has the same architecture as BERT, but uses a byte-level BPE as a tokenizer (same as GPT-2) and uses a different pretraining scheme.
 
RoBERTa doesn’t have token_type_ids, you don’t need to indicate which token belongs to which segment. Just separate your segments with the separation token tokenizer.sep_token (or </s>)
 
Same as BERT with better pretraining tricks:
 
dynamic masking: tokens are masked differently at each epoch, whereas BERT does it once and for all
together to reach 512 tokens (so the sentences are in an order than may span several documents)
train with larger batches
use BPE with bytes as a subunit and not characters (because of unicode characters)
CamemBERT is a wrapper around RoBERTa. Refer to this page for usage examples.
 
Resources
A list of official Hugging Face and community (indicated by 🌎) resources to help you get started with RoBERTa. 
If you’re interested in submitting a resource to be included here, please feel free to open a Pull Request and we’ll review
it! The resource should ideally demonstrate something new instead of duplicating an existing resource.

"""

#### 2. Create chunks of `document_txt` variable using recursive text splitter from langchain. Use maximum chunk length of chunk as 200 tokens

#### 3. Create chunks of `document_txt` variable using semantic chunking from langchain. Use maximum chunk length of chunk as 200 tokens

#### 4.  Embed extracted chunks using model object

#### 5. Identify a small embedding model suitable for retrieval usecases from MTEB benchmark and load it using langchain

#### 6. Identify the attribute defining maximum context length supported by the embedding model using loaded model.

####  7.reate a vector storage using langchain for storing `document_txt` chunks and it's embeddings

#### 5. Perform vector search for created vector storage/database. Use following query as input: `base architecture of RoBERTa`